database:
  host: localhost
  port: 5432
  name: replicant
  user: admin
  password: kreslo
  replication-slot-name: myslot
log:
  level: 5
write:
  stdOut:
    enable: true
  http:
    enable: true
    url: http://hh.sk
